swagger: "2.0"
info:
  version: "0.0.1"
  title: House IoT API
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /status:
    x-swagger-router-controller: device
    get:
      description: Returns device status
      # used as the method name of the controller
      operationId: getStatus
      tags:
        - device
      parameters:
        - name: deviceName
          in: query
          description: The name of the device
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /value:
    x-swagger-router-controller: device
    get:
      description: Returns device value
      # used as the method name of the controller
      operationId: getValue
      tags:
        - device
      parameters:
        - name: deviceName
          in: query
          description: The name of the device
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
